[package]
name = "ridl"
version = "0.1.0"
authors = ["David Detweiler <detweild@uci.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proc-macro2 = ""

[dependencies.syn]
version = "1.0.14"
features = ["full"]