[package]
name = "nvme"
version = "0.1.0"
authors = ["RedLeaf Team"]
edition = "2018"

[lib]
crate-type = ["staticlib"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
debug = true

[dependencies]
syscalls = { path = "../../../sys/interfaces/syscalls", version = "0.1.0" }
libsyscalls = { path = "../../../sys/lib/libsyscalls", version = "0.1.0" }
libtime = { path = "../../../sys/lib/libtime", version = "0.1.0" }
console = { path = "../../../sys/lib/console", version = "0.1.0" }
malloc = { path = "../../../sys/lib/malloc", version = "0.1.0" }
spin = "0.5.2"
bitflags = "1.0.4"
byteorder = { version = "1.2", default-features = false }
serde_derive = "1.0.101"
nvme_device = { path = "../../../sys/interfaces/device/nvme", version = "0.1.0" }
pci_driver = { path = "../../../sys/interfaces/dev/pci/pci_driver", version = "0.1.0" }
usr = { path = "../../../sys/interfaces/usr", version = "0.1.0" }
protocol = { path = "../../../sys/interfaces/protocol", version = "0.1.0" }
platform = { path = "../../../sys/interfaces/platform", version = "0.1.0" }
libdma = { path = "../../../sys/lib/libdma", version = "0.1.0" }
rref = { path = "../../lib/rref", version = "0.1.0" }
b2histogram = "1.0"

[dependencies.lazy_static]
version = "1.3.0"
features = ["spin_no_std"]

[dependencies.num-traits]
version = "0.2.8"
default-features = false
